### ISSUE TITLE
Build core library for arm

### ISSUE THREAD

**Issue by kovdan01** [kovdan01/melon#37]

**Comment by kovdan01** [comment]
Building is now done in an archlinux docker container with prebuilt dependencies (see #64).
**TODO:**
* Write JNI wrappers
* Get rid of docker containers because of their redundancy and large weight, build and cache dependencies directly on GitHub Actions build agents instead

**Comment by kovdan01** [comment]
@RomanAnchugov **TODO**:
* [ ] In core library write functions that receive/return:
  * [x] `int`
  * [x] `double`
  * [x] some fixed-width types (for ex., `std::uint64_t`)
  * [x] simple C++ objects, such as `std::vector` and `std::string` (or investigate how to wrap it if impossible)
  * [x] C-style strings (`const char*), byte buffers
  * [ ] aggregates (simple structs that can contain all above, including other aggregates)
* [ ] Investigate the ownership model:
  * [x] If there is a malloc-like function, that allocates some resource that a caller must then free, how to properly use such functions from Java code.
  * [ ] Is it possible to transfer ownership from Java object to the native code? Something like move-semantics in C++, but between Java and C++.
  * [ ] How to use a function has out-parameter(s) (non-const pointer or l-value reference) properly?
* [ ] Is C++ supported in JNI or we have to provide an interface in C inside `extern "C"`?
* [ ] **REQUIRED**: use dependencies (boost, cyrus-sasl, yaml-cpp, etc, boost - obligatory) in your native functions. Use both inline and pre-compiled functions (or, maybe, inline functions are not supported in JNI, need further investigation)
